gems:
  - jekyll-gist
  - jekyll-sitemap

title: Nicolay Hvidsten
permalink: /blog/:year/:month/:day/:title
encoding: utf-8
markdown: kramdown
highlighter: pygments
kramdown:
  input: GFM
  hard_wrap: false

navigation:
  - text: Blog
    url:  /blog/
  - text: Portfolio
    url:  /portfolio/
  - text: Books
    url:  /books/
  - text: Quotes
    url:  /quotes/
  - text: Now
    url:  /now/

sass:
  sass_dir: _sass
  style: compressed

exclude: [
          'haml.rb', 'node_modules', 'CNAME', 'publish.sh', 'package.json',
          'Gemfile', 'Gemfile.lock'
         ]

