plugins:
  - jekyll-gist
  - jekyll-sitemap

title: Nicolay Hvidsten
permalink: /blog/:year/:month/:day/:title
encoding: utf-8
markdown: kramdown
url: https://www.nico.cool
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

navigation:
  - text: Blog
    url:  /blog/
  - text: Portfolio
    url:  /portfolio/
  - text: Talks
    url:  /talks/
  - text: Books
    url:  /books/
  - text: Quotes
    url:  /quotes/

source: build 

