safe: true
lsi: false
permalink: /blog/:year/:month/:day/:title
encoding: utf-8
markdown: kramdown
kramdown:
  input: GFM
  use_coderay: true
  hard_wrap: true

navigation:
  - text: Blog
    url:  /blog/
  - text: Portfolio
    url: /portfolio/
  - text: Culture
    url: /culture/
  - text: Philosophy
    url: /philosophy/
  - text: Quotes
    url: /quotes/

sass:
  sass_dir: _sass
  style: compressed

exclude: ['sprockets.rb']
