gems:
  - jekyll-gist

title: Nicolay Hvidsten
permalink: /blog/:year/:month/:day/:title
encoding: utf-8
markdown: kramdown
highlighter: rouge 
kramdown:
  input: GFM
  hard_wrap: false

navigation:
  - text: Blog
    url:  /blog/
  - text: Portfolio
    url:  /portfolio/
  - text: Library
    url:  /library/
  - text: Quotes
    url:  /quotes/

sass:
  sass_dir: _sass
  style: compressed

exclude: ['sprockets.rb', 'node_modules']

