safe: true
lsi: false
highlighter: pygments
encoding: utf-8
markdown: redcarpet
redcarpet:
  extensions: ["hard_wrap"]

sass:
  sass_dir: _sass
  style: compressed

exclude: ['sprockets.rb', 'sprockets_demo.rb']
